### ISSUE TITLE
How to make a blacklist

### ISSUE THREAD

**Issue by Y-ogativity** [adomingues/redl_domingues_et_al_dev_2020#1]
Hi, Thank you for providing a blacklist in the zebrafish genome.  Would you like to let me know how you created the blacklist?  I am looking for a blacklist in zebrafish to assess biologically relevant and true signals in my ATAC-seq/ChIP-seq data.

**Comment by adomingues** [comment]
Hi Yohey,


firstly I need to clarify that this list may or may not conform to the [ENCODE](https://www.encodeproject.org/annotations/ENCSR636HFF/) definition, but I would say that it's quite close.

I created the _Danio rerio_ blacklist manually from 3 sources:

- Annotated rRNA
- de novo seacrh of unannotated rRNA loci
- rn7sk locus

Below is the description of how it was generated.

--- 
Before we even started this paper, one of our colleagues noticed that the annotation of 5.8S is incomplete in _Danio rerio_, and NCBI sequences for 5.8S are all partial. Looking further into RNA read density around the partial rRNA loci and blasting of the Salmon rRNA (closely related and well annotated rRNA) he suggested finding the locations of 5.8S rRNA and extending them by 12Kb on either side would give a good estimate of the full loci.

In view of the above, in NCBI I searched for:

> "Danio rerio"[Organism] AND "ribosomal RNA"[Title]

and BLATed the sequence NR_145818.1. This resulted in 13 loci in Zv10, which was downloaded as `Danio_rerio.danRer10.GRCz10.UCSC.rRNA58S.psl` and then converted to bed:

```bash
cat Danio_rerio.danRer10.GRCz10.UCSC.rRNA58S.psl c | cut -f1-6 | awk  'BEGIN {OFS='\t'} {if ($5 > 50) print $0}' > Danio_rerio.danRer10.GRCz10.UCSC.rRNA58S.bed
```

And extended 12kb:

```bash
cat Danio_rerio.danRer10.GRCz10.UCSC.rRNA58S.bed \
    | slopBed -i stdin -b 12000 -g danRer10.chrom.sizes \
    > Danio_rerio.danRer10.GRCz10.UCSC.rRNA58S.12kb.bed
cat Danio_rerio.danRer10.GRCz10.UCSC.rRNA58S.12kb.bed
```

Some matches that where too small to make sense (< 50 bp) were removed.

This was not the last of it, because while browsing the total RNA-seq data (PGCs) I notice that some regions, not annotated as rRNA where highly abundant. BLATing these revealed that these where the large subunit ribosomal ribonucleic acid (LSU rRNA), not yet annotated. To get these out of our data I similar indicated above with some modifications because I couldn't remember how to download the psl in blat (Yeah I know, document, document, document):

- took the sequence from repbase;
- BLAT to find all locations
- create custom track
- download custom track as bed

the bed file also contains the sequence. I was not extended because looking in IGV it seems like this unit is very well defined. Also the two files, containing rRNA58S and SU-rRNA_Hsa, have overlapping coordinates, but do not contain the same locations. Putting these together shoult contain most of the rRNA loci:

```bash
(cat Danio_rerio.danRer10.GRCz10.UCSC.rRNA58S.12kb.bed; cut -f1-6 Danio_rerio.danRer10.GRCz10.UCSC.SU-rRNA_Hsa.seq.bed) | sortBed -i stdin > Danio_rerio.danRer10.GRCz10.UCSC.rRNA.bed
```

Other contaminants, or regions which are highly expressed are the **rn7sk** locus, from where the second highest expression peak comes from.

The final blacklist file (`contaminants.bed`) was put together with:

```bash
(grep rn7sk ../Danio_rerio.GRCz10.80.chrom.TR.so.gtf | awk '$3 == "transcript"' | gtf2bed | cut -f 1-6; cat Danio_rerio.danRer10.GRCz10.UCSC.rRNA.bed) | sortBed -i stdin > Danio_rerio.danRer10.GRCz10.contaminants.bed
```

I hope this helps.

António

**Comment by Y-ogativity** [comment]
Hi António,

Thank you very much for your detailed explanations. I understand that you made a blacklist specialized for total RNA-seq.  In this sequencing experiment, I agree with your method of making the blacklist. On the other hand, for my purpose (ATAC-seq, ChIP-seq), reads are mapped mainly to non-annotated regions. My understanding is that blacklists in ENCODE contain a set of regions where bad sequence assembly quality results in an erogenous signal, which means ENCODE blacklist is a comprehensive list of poorly assembled regions. I asked about the availability of a prevalent blacklist in zebrafish in [Twitter](https://twitter.com/yoheiogawa4/status/1464286058791723009?s=21). I hope that information helps you.  

Yohei
